version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\grafana\grafana-cli

environment:
  nodejs_version: "4"
  GOPATH: c:\gopath

install:
  # install gcc (needed for sqlite3)
  - choco install -y mingw
  - set PATH=C:\tools\mingw64\bin;%PATH%
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go build

#build_script:
#  - go run build.go build

#artifacts:
#  - path: dist/*
#    name: binzip
